allowBuilds:
  sharp: set this to true or false
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.106.0'
  - '@supabase/functions-js@2.106.0'
  - '@supabase/postgrest-js@2.106.0'
  - '@supabase/realtime-js@2.106.0'
  - '@supabase/storage-js@2.106.0'
  - '@supabase/supabase-js@2.106.0'
